spring:
  config:
    import:
      - classpath:netty-based.yaml
      - classpath:tomcat-based.yaml
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowedHeaders:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
              - HEAD
            allowedOriginPatterns:
              - "*"
            exposedHeaders:
              - "Content-Disposition"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    use-root-path: true
    urls:
      - url: /swagger/tomcat-based/v3/api-docs
        name: Tomcat Based
      - url: /swagger/netty-based/v3/api-docs
        name: Netty Based